package org.example.exception;

public enum ErrorType {
    PLEASE_COMPLETE_ALL_FIELDS,

    INVALID_LOGIN,

    EMAIL_ALREADY_REGISTERED,
    USERNAME_ALREADY_EXISTS,
    PASSWORD_MISMATCH,
    INVALID_EMAIL_FORMAT,
    USERNAME_TOO_SHORT,
    INVALID_PASSWORD_FORMAT,

    EMAIL_NOT_FOUND,

    INVALID_CODE,
    OTP_EXPIRED,
    CHECK_TERMS_BOX,
    FAIL_TO_SEND_EMAIL,
    INVALID_PHONE_NUMBER,

    CODE_SENT_SUCCESS
}